### ISSUE TITLE
New Google Play Store instatnce

### ISSUE THREAD

**Issue by moisesbinzie** [CodesFirst/new_version_plus#11]
Once you click "update" on the alert dialogue, it's opening a new instance of Play Store. It's not associating the device current signed in account within the app. It's initiation a new instance of Google play that requires to be signed in. And if you sign in, it doesnt show you an update, it only shows an install button on the Play Store to make a fresh installtion, as if you don't already have the app installed.

here is my code

```
  final newVersion = NewVersionPlus();

  _checkVersion() async {
    newVersion.showAlertIfNecessary(context: context);
  }

  @override
  void initState() {
    _checkVersion();
    super.initState();
  }

  @override
  void dispose() {
    _checkVersion();
    super.dispose();
  }
```

**Comment by pewiher** [comment]
Correct, that is because it opens with the default platform of the device and not with the store, a new parameter was added for the function:

LaunchModeVersion.external (With an external application suitable for the link in this case the playstore)

LaunchModeVersion.normal

This update will be available from version 0.0.5, for now it is recommended that you apply your own logic using the (getVersionStatus) method of the package.
